name: Continuous Integration
on:
  - push
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.6.1

      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          cache: "poetry"

      - run: poetry install

      - run: poetry run ruff check --output-format=github

      - run: poetry run mypy

      - run: poetry run pytest
